# SPDX-License-Identifier: Apache-2.0
# nix_gnat.bzl
#
# A Nix-backed Bazel Ada toolchain, configured from MODULE.bazel via the
# `nix_gnat` module extension (see extensions.bzl).

GnatToolchainInfo = provider(
    doc = "Information about the GNAT toolchain.",
    fields = {
        "gnatmake": "Path to the gnatmake executable.",
        "gnatbind": "Path to the gnatbind executable.",
        "gnatlink": "Path to the gnatlink executable.",
        "gnat": "Path to the gnat executable.",
        "gcc": "Path to the gcc wrapper.",
        "all_files": "A list of all files required by the toolchain.",
    },
)

_TOOLS = [
    "gcc",
    "g++",
    "cpp",
    "ld",
    "ar",
    "as",
    "nm",
    "objcopy",
    "objdump",
    "strip",
    "ranlib",
    "gcov",
    "gnat",
    "gnatmake",
    "gnatbind",
    "gnatlink",
]

def _nix_gnat_toolchain_impl(ctx):
    info = GnatToolchainInfo(
        gnatmake = ctx.file.gnatmake,
        gnatbind = ctx.file.gnatbind,
        gnatlink = ctx.file.gnatlink,
        gnat = ctx.file.gnat,
        gcc = ctx.file.gcc,
        all_files = ctx.files.all_files,
    )
    return [platform_common.ToolchainInfo(gnatinfo = info)]

nix_gnat_toolchain = rule(
    implementation = _nix_gnat_toolchain_impl,
    attrs = {
        "gnatmake": attr.label(allow_single_file = True, executable = True, cfg = "exec"),
        "gnatbind": attr.label(allow_single_file = True, executable = True, cfg = "exec"),
        "gnatlink": attr.label(allow_single_file = True, executable = True, cfg = "exec"),
        "gnat": attr.label(allow_single_file = True, executable = True, cfg = "exec"),
        "gcc": attr.label(allow_single_file = True, executable = True, cfg = "exec"),
        "all_files": attr.label(allow_files = True),
    },
)

def _ada_binary_impl(ctx):
    toolchain = ctx.toolchains["@rules_nix//gnat:toolchain_type"]
    gnatinfo = toolchain.gnatinfo

    output_executable = ctx.actions.declare_file(ctx.label.name)
    srcs = ctx.files.srcs

    # Find the wrapper directory to set PATH
    wrapper_dir = gnatinfo.gnatmake.dirname

    cmd = """
export PATH={wrapper_dir}:$PATH
gnatmake -q {src} -o {out}
""".format(
        wrapper_dir = wrapper_dir,
        src = srcs[0].path,
        out = output_executable.path,
    )

    ctx.actions.run_shell(
        inputs = srcs + gnatinfo.all_files,
        outputs = [output_executable],
        command = cmd,
        use_default_shell_env = True,
    )

    return [DefaultInfo(
        executable = output_executable,
        files = depset([output_executable]),
    )]

ada_binary = rule(
    implementation = _ada_binary_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = [".adb", ".ads"]),
    },
    executable = True,
    toolchains = ["@rules_nix//gnat:toolchain_type"],
)

_GENERATED_BUILD = """# Generated by rules_nix nix_gnat extension. Do not edit.
load("@rules_nix//:nix_gnat.bzl", "nix_gnat_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "wrappers",
    srcs = glob(["bin/**"]),
)

nix_gnat_toolchain(
    name = "nix_gnat_info",
    gnatmake = "bin/gnatmake",
    gnatbind = "bin/gnatbind",
    gnatlink = "bin/gnatlink",
    gnat = "bin/gnat",
    gcc = "bin/gcc",
    all_files = ":wrappers",
)

toolchain(
    name = "toolchain",
    toolchain = ":nix_gnat_info",
    toolchain_type = "@rules_nix//gnat:toolchain_type",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)
"""

def _find_store_bin(repository_ctx, pattern):
    for entry in repository_ctx.path("nix/store").readdir():
        if pattern in entry.basename:
            return "/nix/store/{}/bin".format(entry.basename)
    return None

def _nix_gnat_repo_impl(repository_ctx):
    wrapper = repository_ctx.path(repository_ctx.attr._nix_wrapper)
    installable = repository_ctx.attr.installable

    build = repository_ctx.execute(
        [str(wrapper), "build", "--no-link", "--print-out-paths", installable],
        timeout = 3600,
        quiet = False,
    )
    if build.return_code != 0:
        fail("nix_gnat: failed to build {}:\n{}".format(installable, build.stderr))
    lines = [l for l in build.stdout.splitlines() if l]
    if not lines:
        fail("nix_gnat: `nix build` printed no output path for " + installable)
    store_out = lines[-1]
    guest_out = "/nix/store/" + store_out.rsplit("/", 1)[-1]

    info = repository_ctx.execute(
        [str(wrapper), "path-info", "-r", guest_out],
        timeout = 1200,
    )
    if info.return_code != 0:
        fail("nix_gnat: failed to query closure:\n" + info.stderr)
    closure = [p for p in info.stdout.splitlines() if p]

    repository_ctx.execute(["mkdir", "-p", "nix/store"])
    for p in closure:
        if not repository_ctx.path(p).exists:
            continue
        cp = repository_ctx.execute(["cp", "-a", p, "nix/store/"])
        if cp.return_code != 0:
            fail("nix_gnat: failed to copy {}:\n{}".format(p, cp.stderr))

    parts = []
    for pat in ["gnat-wrapper", "gcc-wrapper", "binutils-wrapper", "coreutils"]:
        b = _find_store_bin(repository_ctx, pat)
        if b:
            parts.append(b)
    guest_pkg = "/nix/store/" + store_out.rsplit("/", 1)[-1]
    if guest_pkg + "/bin" not in parts:
        parts.insert(0, guest_pkg + "/bin")
    parts += ["/usr/bin", "/bin"]
    guest_path = ":".join(parts)

    for tool in _TOOLS:
        repository_ctx.template(
            "bin/" + tool,
            repository_ctx.attr._wrapper,
            substitutions = {"%{GUEST_PATH}%": guest_path},
            executable = True,
        )

    cp_bwrap = repository_ctx.execute(
        ["cp", str(repository_ctx.path(repository_ctx.attr._bwrap)), "bwrap"],
    )
    if cp_bwrap.return_code != 0:
        fail("nix_gnat: failed to copy bwrap:\n" + cp_bwrap.stderr)
    repository_ctx.execute(["chmod", "+x", "bwrap"])

    repository_ctx.file("BUILD.bazel", content = _GENERATED_BUILD)

nix_gnat_repo = repository_rule(
    implementation = _nix_gnat_repo_impl,
    doc = "Realizes a Nix-backed GNAT toolchain into an external repository.",
    attrs = {
        "installable": attr.string(
            mandatory = True,
        ),
        "_nix_wrapper": attr.label(
            default = Label("@nix_bootstrap//:nix_wrapper.sh"),
        ),
        "_wrapper": attr.label(
            default = Label("//:nix_cc_wrapper.sh.tpl"),
            allow_single_file = True,
        ),
        "_bwrap": attr.label(
            default = Label("@nix_bootstrap//:bwrap"),
            allow_single_file = True,
        ),
    },
)
