# SPDX-License-Identifier: Apache-2.0
# nix_cc.bzl
#
# A Nix-backed Bazel C/C++ toolchain, configured from MODULE.bazel via the
# `nix_cc` module extension (see extensions.bzl). This is the rules_nix analog
# of tweag/rules_nixpkgs's nixpkgs_cc_configure, adapted to this project's
# ephemeral, host-Nix-free model: the compiler closure is realized once into a
# generated repository and every tool is invoked through a bwrap wrapper that
# overlays that closure at /nix/store (see nix_cc_wrapper.sh.tpl).

load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load(
    "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "feature",
    "flag_group",
    "flag_set",
    "tool_path",
)

# Tools exposed to Bazel as cc_toolchain tool_paths. Each is a copy of the
# generic wrapper named after the tool; the wrapper resolves the real binary
# from the bundled gcc/binutils wrappers via PATH.
_TOOLS = [
    "gcc",
    "g++",
    "cpp",
    "ld",
    "ar",
    "as",
    "nm",
    "objcopy",
    "objdump",
    "strip",
    "ranlib",
    "gcov",
]

def _nix_cc_toolchain_config_impl(ctx):
    tool_paths = [
        tool_path(name = "gcc", path = "bin/gcc"),
        tool_path(name = "ld", path = "bin/ld"),
        tool_path(name = "ar", path = "bin/ar"),
        tool_path(name = "cpp", path = "bin/cpp"),
        tool_path(name = "gcov", path = "bin/gcov"),
        tool_path(name = "nm", path = "bin/nm"),
        tool_path(name = "objdump", path = "bin/objdump"),
        tool_path(name = "objcopy", path = "bin/objcopy"),
        tool_path(name = "strip", path = "bin/strip"),
    ]

    # Bazel links via the "gcc" (C) driver, so the C++ standard library is not
    # pulled in automatically; add it (and libm) to link actions. Other default
    # include/lib flags are baked into the Nix cc-wrapper.
    link_flags = feature(
        name = "default_link_flags",
        enabled = True,
        flag_sets = [flag_set(
            actions = [
                ACTION_NAMES.cpp_link_executable,
                ACTION_NAMES.cpp_link_dynamic_library,
                ACTION_NAMES.cpp_link_nodeps_dynamic_library,
            ],
            flag_groups = [flag_group(flags = ["-lstdc++", "-lm"])],
        )],
    )
    features = [
        feature(name = "supports_dynamic_linker", enabled = True),
        feature(name = "supports_pic", enabled = True),
        link_flags,
    ]

    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        toolchain_identifier = "nix-gcc",
        host_system_name = "local",
        target_system_name = "local",
        target_cpu = "k8",
        target_libc = "unknown",
        compiler = "gcc",
        abi_version = "unknown",
        abi_libc_version = "unknown",
        tool_paths = tool_paths,
        features = features,
        # The compiler's system headers live in the overlaid Nix store; allow
        # includes from there so Bazel's header validation passes.
        cxx_builtin_include_directories = ctx.attr.builtin_include_directories,
    )

nix_cc_toolchain_config = rule(
    implementation = _nix_cc_toolchain_config_impl,
    doc = "Generates a cc_toolchain_config for a Nix-backed C/C++ toolchain.",
    attrs = {
        "builtin_include_directories": attr.string_list(
            doc = "Directories allowed for C++ builtin includes.",
            default = ["/nix/store"],
        ),
    },
)

_GENERATED_BUILD = """# Generated by rules_nix nix_cc extension. Do not edit.
load("@rules_cc//cc:defs.bzl", "cc_toolchain")
load("@rules_nix//:nix_cc.bzl", "nix_cc_toolchain_config")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "wrappers",
    srcs = glob(["bin/**"]),
)

filegroup(name = "empty")

nix_cc_toolchain_config(name = "nix_cc_config")

cc_toolchain(
    name = "nix_cc",
    toolchain_config = ":nix_cc_config",
    all_files = ":wrappers",
    ar_files = ":wrappers",
    as_files = ":wrappers",
    compiler_files = ":wrappers",
    dwp_files = ":empty",
    linker_files = ":wrappers",
    objcopy_files = ":wrappers",
    strip_files = ":wrappers",
    supports_param_files = 0,
)

toolchain(
    name = "toolchain",
    toolchain = ":nix_cc",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)
"""

def _find_store_bin(repository_ctx, pattern):
    """Returns the guest /nix/store/<dir>/bin for the first store entry whose
    name contains `pattern`, or None."""
    for entry in repository_ctx.path("nix/store").readdir():
        if pattern in entry.basename:
            return "/nix/store/{}/bin".format(entry.basename)
    return None

def _nix_cc_repo_impl(repository_ctx):
    print("DEBUG: entering _nix_cc_repo_impl for " + repository_ctx.name)
    wrapper = repository_ctx.path(repository_ctx.attr._nix_wrapper)
    installable = repository_ctx.attr.installable

    # Realize the compiler closure (shares the persistent store seeded by the
    # build-time wrapper, because the repo dir sits at the same depth under the
    # output_base as the execroot does).
    build = repository_ctx.execute(
        [str(wrapper), "build", "--no-link", "--print-out-paths", installable],
        timeout = 3600,
        quiet = False,
    )
    if build.return_code != 0:
        print("nix_cc: build failed")
        print("stdout: " + build.stdout)
        print("stderr: " + build.stderr)
        fail("nix_cc: failed to build {}:\n{}".format(installable, build.stderr))
    lines = [l for l in build.stdout.splitlines() if l]
    if not lines:
        fail("nix_cc: `nix build` printed no output path for " + installable)
    store_out = lines[-1]
    guest_out = "/nix/store/" + store_out.rsplit("/", 1)[-1]

    # Query the closure of the realized output path (not the installable) so we
    # list only present store paths -- querying the installable can surface
    # sibling outputs (e.g. -man) that were never substituted.
    info = repository_ctx.execute(
        [str(wrapper), "path-info", "-r", guest_out],
        timeout = 1200,
    )
    if info.return_code != 0:
        print("nix_cc: path-info failed")
        print("stdout: " + info.stdout)
        print("stderr: " + info.stderr)
        fail("nix_cc: failed to query closure:\n" + info.stderr)
    closure = [p for p in info.stdout.splitlines() if p]

    repository_ctx.execute(["mkdir", "-p", "nix/store"])
    for p in closure:
        # The wrapper rewrites present guest paths to their host location; skip
        # anything that did not resolve to a real file.
        if not repository_ctx.path(p).exists:
            continue
        cp = repository_ctx.execute(["cp", "-a", p, "nix/store/"])
        if cp.return_code != 0:
            fail("nix_cc: failed to copy {}:\n{}".format(p, cp.stderr))

    # Build the guest PATH the wrappers use: the gcc/binutils cc-wrappers (so
    # the driver finds `as`/`ld`) plus coreutils.
    parts = []
    for pat in ["gcc-wrapper", "binutils-wrapper", "coreutils"]:
        b = _find_store_bin(repository_ctx, pat)
        if b:
            parts.append(b)
    guest_pkg = "/nix/store/" + store_out.rsplit("/", 1)[-1]
    if guest_pkg + "/bin" not in parts:
        parts.insert(0, guest_pkg + "/bin")
    parts += ["/usr/bin", "/bin"]
    guest_path = ":".join(parts)

    for tool in _TOOLS:
        repository_ctx.template(
            "bin/" + tool,
            repository_ctx.attr._wrapper,
            substitutions = {"%{GUEST_PATH}%": guest_path},
            executable = True,
        )

    repository_ctx.file("BUILD.bazel", content = _GENERATED_BUILD)

nix_cc_repo = repository_rule(
    implementation = _nix_cc_repo_impl,
    doc = """Realizes a Nix-backed C/C++ toolchain into an external repository.

Realizes the full closure of the compiler from nixpkgs, copies it into
the external repository, and generates a cc_toolchain definition.
""",
    attrs = {
        "installable": attr.string(
            doc = "Nix installable providing the C/C++ compiler (e.g. 'nixpkgs#gcc').",
            mandatory = True,
        ),
        "_nix_wrapper": attr.label(
            doc = "Internal Nix wrapper script.",
            default = Label("@nix_bootstrap//:nix_wrapper.sh"),
        ),
        "_wrapper": attr.label(
            doc = "Template for individual tool wrappers (e.g. gcc, ld).",
            default = Label("//:nix_cc_wrapper.sh.tpl"),
            allow_single_file = True,
        ),
    },
)
